export const ROUTE_PATHS = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/registro',
    ACCESS_DENIED: '/403',
    STATES: '/estados',
  },
  CLIENTE: {
    STORE: '/tienda',
    PRODUCT_DETAIL: '/tienda/:id',
    CART: '/carrito',
    CHECKOUT: '/checkout',
    CHECKOUT_CONFIRMATION: '/checkout/confirmacion',
    ORDERS: '/mis-ordenes',
    ORDER_DETAIL: '/mis-ordenes/:id',
    PROFILE: '/perfil',
  },
  DASHBOARD: {
    HOME: '/dashboard',
    PRODUCTS: '/dashboard/productos',
    PROVIDERS: '/dashboard/proveedores',
    SALES: '/dashboard/ventas',
    NEW_SALE: '/dashboard/ventas/nueva',
    SALE_DETAIL: '/dashboard/ventas/:id',
    CUSTOMERS: '/dashboard/clientes',
    USERS: '/dashboard/usuarios',
    EMPLOYEES: '/dashboard/empleados',
    INVENTORY: '/dashboard/inventario',
    RECEPTIONS: '/dashboard/inventario/recepciones',
    CRITICAL_STOCK: '/dashboard/inventario/stock-critico',
    REPORTS: '/dashboard/reportes',
    PROFILE: '/dashboard/perfil',
  },
  PROVEEDOR: {
    HOME: '/proveedor',
    PRODUCTS: '/proveedor/productos',
    DELIVERIES: '/proveedor/entregas',
    NEW_DELIVERY: '/proveedor/entregas/nueva',
    PROFILE: '/proveedor/perfil',
  },
} as const;
